apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: pipeline-hello-world-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.6.2, pipelines.kubeflow.org/pipeline_compilation_time: '2021-05-31T17:17:26.946440',
    pipelines.kubeflow.org/pipeline_spec: '{"name": "pipeline_hello_world"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.6.2}
spec:
  entrypoint: pipeline-hello-world
  templates:
  - name: get-op1
    container:
      args: []
      command:
      - sh
      - -ec
      - |
        program_path=$(mktemp)
        printf "%s" "$0" > "$program_path"
        python3 -u "$program_path" "$@"
      - |
        def get_op1():
            op1()

        import argparse
        _parser = argparse.ArgumentParser(prog='Get op1', description='')
        _parsed_args = vars(_parser.parse_args())

        _outputs = get_op1(**_parsed_args)
      image: python:3.7
    metadata:
      labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.6.2, pipelines.kubeflow.org/pipeline-sdk-type: kfp}
      annotations: {pipelines.kubeflow.org/component_spec: '{"implementation": {"container":
          {"args": [], "command": ["sh", "-ec", "program_path=$(mktemp)\nprintf \"%s\"
          \"$0\" > \"$program_path\"\npython3 -u \"$program_path\" \"$@\"\n", "def
          get_op1():\n    op1()\n\nimport argparse\n_parser = argparse.ArgumentParser(prog=''Get
          op1'', description='''')\n_parsed_args = vars(_parser.parse_args())\n\n_outputs
          = get_op1(**_parsed_args)\n"], "image": "python:3.7"}}, "name": "Get op1"}',
        pipelines.kubeflow.org/component_ref: '{}'}
  - name: get-op2
    container:
      args: []
      command:
      - sh
      - -ec
      - |
        program_path=$(mktemp)
        printf "%s" "$0" > "$program_path"
        python3 -u "$program_path" "$@"
      - |
        def get_op2():
            op2("k8s")

        import argparse
        _parser = argparse.ArgumentParser(prog='Get op2', description='')
        _parsed_args = vars(_parser.parse_args())

        _outputs = get_op2(**_parsed_args)
      image: python:3.7
    metadata:
      labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.6.2, pipelines.kubeflow.org/pipeline-sdk-type: kfp}
      annotations: {pipelines.kubeflow.org/component_spec: '{"implementation": {"container":
          {"args": [], "command": ["sh", "-ec", "program_path=$(mktemp)\nprintf \"%s\"
          \"$0\" > \"$program_path\"\npython3 -u \"$program_path\" \"$@\"\n", "def
          get_op2():\n    op2(\"k8s\")\n\nimport argparse\n_parser = argparse.ArgumentParser(prog=''Get
          op2'', description='''')\n_parsed_args = vars(_parser.parse_args())\n\n_outputs
          = get_op2(**_parsed_args)\n"], "image": "python:3.7"}}, "name": "Get op2"}',
        pipelines.kubeflow.org/component_ref: '{}'}
  - name: pipeline-hello-world
    dag:
      tasks:
      - {name: get-op1, template: get-op1}
      - name: get-op2
        template: get-op2
        dependencies: [get-op1]
  arguments:
    parameters: []
  serviceAccountName: pipeline-runner
